### ISSUE TITLE
[DESIGN] - ajustements

### ISSUE THREAD

**Issue by cecileropital** [coopTilleuls/rustinelibre#890]
- [x] uniformiser les comportements des boutons au hover
- [x] **Page d'un réparateur** : la photo de description en bas flotte #906 
- [x] **Page d'accueil** : revoir le design du bandeau invitant à installer la webapp sur l'écran d'accueil #930 
- [x] **Page d'accueil** : le bandeau doit pousser le contenu et non le recouvrir. Actuellement, on ne voit plus le menu (identique sur mobile et sur Desktop)
- [x] **Page d'accueil** : menu bas, prévoir la couleur orange au hover #904 
- [x] **Recherche réparateur** : passer les pin map en orange et en marron au hover #932 
- [x] **sr admin** : mettre le bg en orange et ajouter le logo (sur fond coloré) au dessus de l'encart "se connecter" et éventuellement, ajouter admin sous le logo #908 
- [x] **menu bas** : même quand la personne n'est pas connectée, afficher le menu complet avec tous les items cliquables, comme sur le WF #921
